from __future__ import annotations

from typing import Any, Protocol

from app.models.types import PortfolioHolding, PortfolioSnapshot


class CandidateRegistryDonor(Protocol):
    def list_candidates(self) -> list[dict[str, Any]]: ...

    def list_required_fields(self, sleeve_key: str) -> list[dict[str, Any]]: ...

    def resolve_field_truth(self, *, candidate_symbol: str, sleeve_key: str) -> dict[str, dict[str, Any]]: ...

    def compute_candidate_completeness(self, *, candidate: dict[str, Any]) -> dict[str, Any]: ...


class BenchmarkRegistryDonor(Protocol):
    def resolve_benchmark_assignment(self, *, candidate: dict[str, Any], sleeve_key: str) -> dict[str, Any]: ...

    def list_benchmark_registry(self) -> list[dict[str, Any]]: ...

    def build_benchmark_registry_summary(self, *, sleeves: list[dict[str, Any]]) -> dict[str, Any]: ...


class EtfSourceDonor(Protocol):
    def get_source_config(self, symbol: str) -> dict[str, Any] | None: ...

    def get_document_record(self, symbol: str, *, use_fixtures: bool = False) -> dict[str, Any]: ...

    def get_holdings_profile(self, symbol: str) -> dict[str, Any] | None: ...

    def get_factsheet_summary(self, symbol: str) -> dict[str, Any] | None: ...

    def get_market_summary(self, symbol: str) -> dict[str, Any] | None: ...

    def get_latest_market_data(self, symbol: str) -> dict[str, Any] | None: ...


class ProviderSnapshotDonor(Protocol):
    def build_cached_payload(self, *, surface_name: str | None = None) -> dict[str, Any]: ...

    def refresh_blueprint(self, *, force_refresh: bool = False) -> dict[str, Any]: ...

    def refresh_daily_brief(self, *, force_refresh: bool = False) -> dict[str, Any]: ...

    def refresh_dashboard(self, *, account_id: str | None = None, force_refresh: bool = False) -> dict[str, Any]: ...


class PortfolioStateDonor(Protocol):
    def list_holdings(self) -> list[PortfolioHolding]: ...

    def latest_snapshot(self) -> PortfolioSnapshot | None: ...

    def list_snapshots(self, *, limit: int = 30) -> list[PortfolioSnapshot]: ...

